### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by jelle619** [Snazzah/SublimeDiscordRP#23] opened 2018-02-03 12:33 UTC
Doesn't seem to be working on macOS for some reason. Restarted Discord, Sublime and my computer several times, but nothing's happening.

**Comment by Snazzah** [comment] 2018-02-14 02:02
You need to give more information than that like giving Discord console logs `Ctrl+Shift+I` (`Option+Command+I` for Mac)

**Comment by yattaro** [comment] 2018-02-19 21:53
Yep, I'm running into similar issues on MacOS 10.13.3.  I think I have a slight clue.  I have my Spotify account connected to Discord and I noticed that my status changes to Sublime after I toggle Spotify playback (start playing -> status = "Playing Sublime Text").  The status also remains after I close Sublime until I restart Discord, so I have a feeling it's something to do with the status change is actually triggered on MacOS.  Attached my Discord log below.
[discordapp.com-1519076700990.log](https://github.com/Snazzah/SublimeDiscordRP/files/1738241/discordapp.com-1519076700990.log)

**Comment by 1byte2bytes** [comment] 2018-02-20 05:16
Can confirm it's not working for me on macOS 10.12.6. I'm using Sublime Text 3.0, build 3143. DiscordRP version 2.1.0. Installed via Package Control. Checking the console doesn't output any errors. With debug mode I get:

```
[Discord Rich Presence._logging] INFO: Changing log level from 'WARNING' to 'DEBUG'
[Discord Rich Presence.discord_ipc] DEBUG: sending {'v': 1, 'client_id': '389368374645227520'}
[Discord Rich Presence.discord_ipc] DEBUG: received {'cmd': 'DISPATCH', 'data': {'v': 1, 'config': {'cdn_host': 'cdn.discordapp.com', 'environment': 'production', 'api_endpoint': '//canary.discordapp.com/api'}}, 'evt': 'READY', 'nonce': None}
[Discord Rich Presence.discord_ipc] INFO: connected via ID 389368374645227520
[Discord Rich Presence.discord_ipc] DEBUG: sending {'args': {'activity': {'timestamps': {'start': 1519103705.986641}, 'instance': False, 'assets': {'large_image': 'sublime3', 'large_text': 'Sublime Text 3 v3143'}}, 'pid': 26036}, 'cmd': 'SET_ACTIVITY', 'nonce': '42fe5965-bd5d-4bb4-93f3-59d095c3acfe'}
```

**Comment by Snazzah** [comment] 2018-03-14 09:49
@yattaro Your log is some jumbled mess I can't really wrap my head around.
@1byte2bytes Can you go to your Discord Console and find where it says something about IPC errors and screenshot it?

**Comment by 1byte2bytes** [comment] 2018-03-14 12:53
I don't have any IPC errors in my console.

![screen shot 2018-03-14 at 5 46 29 am](https://user-images.githubusercontent.com/12016303/37403217-4cb05006-274b-11e8-841e-d69aee8474d3.png)

Here's an expanded view of those RPC items

![screen shot 2018-03-14 at 5 48 55 am](https://user-images.githubusercontent.com/12016303/37403252-6f56e296-274b-11e8-898d-a60b2662200a.png)

However, as before, even with a C file open in a folder, nothing shows up.

![screen shot 2018-03-14 at 5 49 56 am](https://user-images.githubusercontent.com/12016303/37403302-963b2520-274b-11e8-8ca0-5b481c63f196.png)
----

My Sublime RPC config file is as follows:
```json
{
    "log_level": "DEBUG",
    "details": "{project}",
    "state": "{file}"
}
```

Interestingly, having Sublime Text 3 edit my Sublime RPC config file makes it show up in Discord as it should, but any actual folders do not.

**Comment by FichteFoll** [comment] 2018-03-14 17:02
So far, this seems to be working as intended. The displayed file and project will only change when you modify or save a file, so I assume you just haven't done that when you made the screenshot of the card.

Can you describe a situation where you edit a file (in a project or just any window) after which the card still doesn't show any details? Also, please include a screenshot of the expanded IPC Socket messages when that happens and open the `activity` object in the first message.

**Comment by 1byte2bytes** [comment] 2018-03-14 17:07
I have modified and saved my `main.c` file multiple times and ensured it's connected to Discord. This happens for every project on my Mac.

I do notice this though. This occurs with a completely default set of settings.
![screen shot 2018-03-14 at 10 06 10 am](https://user-images.githubusercontent.com/12016303/37418393-58b3f65e-276f-11e8-8e42-1f20d218cac3.png)

**Comment by FichteFoll** [comment] 2018-03-14 17:18
Ah, that problem has been fixed with https://github.com/Snazzah/SublimeDiscordRP/commit/cd6579588f086f29d6437844407188a8e2cb06e7 there wasn't any release since then. I'll prepare one in a few hours.

**Comment by FichteFoll** [comment] 2018-03-14 20:22
Tagged 2.1.1. Should be available within an hour.

>Edit: an additional note, when I close Sublime my playing status does not go away from Sublime Text. I have tested with both Spotify open and playing and with it not open at all.

Discord itself checks whether the pid we sent during the handshake still exists and recognizes that you stopped playing when the process died. This isn't something we can control either, because even disconnecting the pipe does not make the message disappear, and there is no specific message that we can send.

---

@jelle619, if you are still having issues, please provide a debug log and a screenshot of IPC-related messages in discord's console like @1byte2bytes did.

**Comment by FichteFoll** [comment] 2018-04-10 00:25
Closing due to lack of response.

2.1.2 includes a feature to read potential error messages from the discord client and logs them to the console for better debugging of issues like this.

**Closed by FichteFoll** 2018-04-10 00:25 UTC
Labels: bug, needs clarification
